apiVersion: v1
kind: Service
metadata:
  name: router
  namespace: default
  labels:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: router
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: router
    app.kubernetes.io/instance: router
  ports:
    - name: http
      protocol: TCP
      port: 80        # Cluster-internal service port
      targetPort: 8180