apiVersion: v1
kind: Service
metadata:
  name: hello-rest-service
  labels:
    app: hello-rest
spec:
  type: LoadBalancer
  selector:
    app: hello-rest
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP