apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-scaler
rules:
  # Allow read access to deployments
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch

  # Allow patch and update on deployments and their scale subresource
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
    verbs:
      - patch
      - update