apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobsink-ingress
  namespace: jobs
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: jobsink.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jobsink
                port:
                  number: 8080