apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    replicas: 3
    listeners:
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        authentication:
          type: scram-sha-512
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      auto.create.topics.enable: "false"
    storage:
      type: persistent-claim
      size: 100Gi
      class: premium-rwo
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      class: premium-rwo
  entityOperator:
    topicOperator: {}
    userOperator: {}