apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [server]
    http_port = 3000

    [security]
    admin_user = admin
    admin_password = admin

    [smtp]
    enabled = true
    host = smtp.sendgrid.net:587
    user = apikey
    # Grafana supports environment variable expansion in config:
    # ${ENV_VAR} will be replaced at runtime.
    password = ${SENDGRID_API_KEY}
    from_address = my-from-address
    from_name = Grafana
    skip_verify = false