apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-java-service-envfile
  labels:
    app: test-java-service-envfile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-java-service-envfile
  template:
    metadata:
      labels:
        app: test-java-service-envfile
    spec:
      containers:
        - name: test-java-service
          image: your-registry/your-java-image:latest
          command:
            - /bin/sh
            - -c
            - >
              exec java $JAVA_TOOL_OPTIONS -jar java_j.jar
          envFrom:
            - configMapRef:
                name: java-options
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Always