apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 5m
  chart:
    spec:
      chart: airflow
      version: "8.9.0"
      sourceRef:
        kind: HelmRepository
        name: airflow-helm
        namespace: airflow
  valuesFrom:
    - kind: ConfigMap
      name: airflow-values
      valuesKey: values.yaml