apiVersion: v1
kind: Service
metadata:
  name: otel-collector-prometheus
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  type: ClusterIP
  selector:
    app: opentelemetry
    component: otel-collector
  ports:
    - name: prom-exporter
      port: 8889
      targetPort: 8889