apiVersion: v1
kind: Service
metadata:
  name: telemetry-asterix-adapter-svc
  namespace: utm
  labels:
    app: telemetry-asterix-adapter
spec:
  type: LoadBalancer
  selector:
    app: telemetry-asterix-adapter
  ports:
    - name: udp-telemetry
      protocol: UDP
      port: 1025          # external port (what the ADSB sensor sends to)
      targetPort: 6000    # container's UDP port
  loadBalancerSourceRanges:
    - 71.###.###.###/32   # replace with actual allowed source IP(s)
    - 71.###.###.###/32   # or remove this list entirely to allow all
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4