apiVersion: v1
kind: Pod
metadata:
  name: dir-access-volume-demo
  labels:
    app: dir-access-volume-demo
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
    - name: shared-dir
      emptyDir: {}
  containers:
    - name: writer
      image: busybox:1.28
      command:
        - sh
        - -c
        - |
          mkdir -p /DIR1 && \
          chown root:2000 /DIR1 && \
          chmod 770 /DIR1 && \
          echo "writer can write" >> /DIR1/file.txt && \
          sleep 3600
      volumeMounts:
        - name: shared-dir
          mountPath: /DIR1
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
    - name: reader
      image: busybox:1.28
      command:
        - sh
        - -c
        - |
          ls -ld /DIR1 || echo "no dir"; \
          cat /DIR1/file.txt || echo "no read"; \
          sleep 3600
      volumeMounts:
        - name: shared-dir
          mountPath: /DIR1
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true