apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
  labels:
    app.kubernetes.io/name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kibana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kibana
    spec:
      imagePullSecrets:
        - name: nexus-image-pull-secret
      containers:
        - name: kibana
          image: "abc.xyz.com/bitnami/kibana:8-debian-12"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "https://elasticsearch-master.logging.svc.cluster.local:9200"
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: "/usr/share/kibana/config/certs/ca.crt"
            - name: SERVER_HOST
              value: "0.0.0.0"
          volumeMounts:
            - name: elasticsearch-certs
              mountPath: /usr/share/kibana/config/certs
              readOnly: true
      volumes:
        - name: elasticsearch-certs
          secret:
            secretName: elasticsearch-master-certs
            optional: false