apiVersion: v1
kind: Pod
metadata:
  name: test-non-restarting-pod
  labels:
    app: test-non-restarting
spec:
  restartPolicy: Never
  containers:
    - name: test-container
      image: busybox:1.36
      command: ["sh", "-c", "echo 'Starting test container'; sleep 10; echo 'Exiting with error'; exit 1"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"