apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-curl-demo
  labels:
    app: lifecycle-curl-demo
spec:
  restartPolicy: Always
  containers:
    - name: lifecycle-demo-container
      image: curlimages/curl:8.10.1
      # Example main command; adjust to your real container image/command
      command: ["sh", "-c", "sleep 3600"]
      lifecycle:
        postStart:
          exec:
            command:
              - curl
              - -H
              - Content-Type: application/json
              - -d
              - '{"restarted": true}'
              - -X
              - POST
              - http://localhost:5000/restarted
      # Example resource requests/limits for production readiness
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      # Example security context best practices
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
  # Example pod-level security context
  securityContext:
    fsGroup: 2000