apiVersion: v1
kind: ConfigMap
metadata:
  name: python-memory-demo-defaults-code
  namespace: python-mem-defaults
data:
  main.py: |
    import time

    data = []
    print("Allocating memory in 20 MiB chunks...", flush=True)
    try:
      for i in range(1, 1000):
        data.append(bytearray(20 * 1024 * 1024))
        print(f"Allocated ~{i * 20} MiB so far", flush=True)
        time.sleep(1)
    except MemoryError:
      print("Caught MemoryError in Python", flush=True)
      time.sleep(10)
    finally:
      print("Exiting", flush=True)