apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
    spec:
      containers:
        - name: app
          image: mcr.microsoft.com/dotnet/aspnet:8.0
          ports:
            - containerPort: 80