apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-mock
  namespace: default  # Replace with your namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9090
        - containerPort: 9092
        - containerPort: 9094
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"  # Replace with your Zookeeper service
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://kafka-mock:9090,INSIDE_PLAINTEXT://proxy:19097"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://0.0.0.0:9090,INTERNAL_FAILOVER://0.0.0.0:9092,INSIDE_PLAINTEXT://0.0.0.0:9094"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,INTERNAL_FAILOVER:PLAINTEXT,INSIDE_PLAINTEXT:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"