apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: aws-general-services
  namespace: istio-system
spec:
  hosts:
  - "*.amazonaws.com"
  ports:
  - number: 443
    name: https
    protocol: TLS
  location: MESH_EXTERNAL
  resolution: DNS