apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtest-deployment
  labels:
    app: webtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webtest
  template:
    metadata:
      labels:
        app: webtest
      annotations:
        # This annotation changes with each helm upgrade, forcing pod restart
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: webtest
        image: k3d-registry.localhost:5000/myapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"