apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/app-root: /ui/
  name: app-ingress
  namespace: app
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - app.my-domain.net
      secretName: app-tls
  rules:
  - host: app.my-domain.net
    http:
      paths:
      - path: /\.well-known(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: well-known-static-resources
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-service
            port:
              number: 80