apiVersion: v1
kind: Pod
metadata:
  name: multi-container-isolation
  namespace: default
spec:
  securityContext:
    fsGroup: 2000
  
  initContainers:
  - name: setup-dirs
    image: busybox:1.36
    command:
      - sh
      - -c
      - |
        mkdir -p /shared/DIR1 /shared/DIR2
        chown 1000:2000 /shared/DIR1
        chmod 770 /shared/DIR1
        chown 1001:3000 /shared/DIR2
        chmod 770 /shared/DIR2
    volumeMounts:
    - name: shared-volume
      mountPath: /shared
    securityContext:
      runAsUser: 0
  
  containers:
  # Container for Group 1 users (write access to DIR1)
  - name: group1-container
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: shared-volume
      mountPath: /data
    securityContext:
      runAsUser: 1000
      runAsGroup: 2000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  
  # Container for Group 2 users (read-only via mounting)
  - name: group2-container
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: shared-volume
      mountPath: /data
      readOnly: true  # Entire mount is read-only
    securityContext:
      runAsUser: 1001
      runAsGroup: 3000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
  
  volumes:
  - name: shared-volume
    emptyDir: {}