apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  config.play.ts: |
    const config = {{ tpl (.Values.app.play | mustToPrettyJson) $ | regexReplaceAll "\"([0-9 +\\-*/().]+)\"" "${1}" | indent 6 }}
    export default config;