apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-header-app-configmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-header-app
  template:
    metadata:
      labels:
        app: spring-header-app
    spec:
      containers:
      - name: spring-boot-app
        image: my-registry/my-spring-boot-app:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: app-config
          items:
          - key: application.properties
            path: application.properties