apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportportal-analyzer
  namespace: reportportal
  labels:
    app: reportportal-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportportal-analyzer
  template:
    metadata:
      labels:
        app: reportportal-analyzer
    spec:
      containers:
        - name: analyzer
          # Ensure this image tag matches your currently deployed version
          image: reportportal/service-analyzer:5.5.0
          env:
            # Retrieve the RabbitMQ password from the existing Secret
            - name: RP_AMQP_PASS
              valueFrom:
                secretKeyRef:
                  name: reportportal-rabbitmq
                  key: rabbitmq-password
            
            # FIXED: AMQP_URL now points to the 'reportportal' vhost instead of 'analyzer'
            # Format: amqp://user:password@host:port/vhost
            - name: AMQP_URL
              value: "amqp://rabbitmq:$(RP_AMQP_PASS)@reportportal-rabbitmq.reportportal.svc.cluster.local:5672/reportportal?heartbeat=30"
            
            # Retain other necessary configuration variables
            - name: RP_SERVER_PORT
              value: "8080"
          
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi