apiVersion: apps/v1
kind: Deployment
metadata:
  name: penpot-backend
  namespace: penpot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penpot-backend
  template:
    metadata:
      labels:
        app: penpot-backend
    spec:
      containers:
        - name: penpot-backend
          image: penpotapp/backend:latest
          env:
            - name: PENPOT_PUBLIC_URI
              value: http://penpot-frontend
            # FIX 1: Use the service name "postgres" defined in your Service YAML.
            # FIX 2: Exclude credentials from the URI to prevent parsing errors.
            - name: PENPOT_DATABASE_URI
              value: postgresql://postgres:5432/penpot
            # FIX 3: Supply credentials via separate environment variables.
            - name: PENPOT_DATABASE_USERNAME
              value: penpot
            - name: PENPOT_DATABASE_PASSWORD
              value: penpot
            - name: PENPOT_REDIS_URI
              value: redis://redis:6379
          ports:
            - containerPort: 6060