apiVersion: v1
kind: Service
metadata:
  name: emqx
  labels:
    app: emqx
spec:
  selector:
    app: emqx
  type: ClusterIP
  ports:
    # The HTTP API / Dashboard port
    - name: dashboard
      port: 18083
      targetPort: 18083
      protocol: TCP
      
    # The PLAINTEXT WebSocket Port
    # Ingress sends decrypted traffic here.
    - name: ws-mqtt
      port: 8083
      targetPort: 8083
      protocol: TCP
      
    # The SSL WebSocket Port
    # Usually NOT used by Ingress unless doing SSL Passthrough
    - name: wss-mqtt
      port: 8084
      targetPort: 8084
      protocol: TCP