apiVersion: v1
kind: Service
metadata:
  name: apisix-gateway-service
  namespace: apisix
spec:
  type: LoadBalancer
  selector:
    # Ensure this matches your APISIX pod labels. 
    # Standard Helm installs usually use 'app.kubernetes.io/name: apisix'
    app.kubernetes.io/name: apisix
  ports:
  - name: http
    port: 5678        # The port you expose externally (load balancer)
    targetPort: 9080  # FIXED: Default APISIX HTTP data plane port (was 8090)
    protocol: TCP