apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: file-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: file-reader-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-exec-reader
  apiGroup: rbac.authorization.k8s.io