apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: nginx:latest
          env:
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  # This name must match the name the SealedSecret generates (usually defined in spec.template.metadata.name)
                  name: my-app-prod-secret
                  key: password-key