apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-app
  namespace: default
  labels:
    app: legacy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-app
  template:
    metadata:
      labels:
        app: legacy-app
    spec:
      containers:
        - name: legacy-app
          image: traefik/whoami
          ports:
            - containerPort: 80