apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: default
spec:
  replicas: 1  # Single replica to avoid conflicts
  strategy:
    type: Recreate  # Prevents multiple instances from running simultaneously
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.13.4
        args:
        - --source=ingress
        - --domain-filter=domain.com  # Replace with your domain
        - --provider=aws
        - --policy=sync
        - --aws-zone-type=public
        - --registry=txt
        - --interval=1m
        - --log-level=debug
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi