apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: job-trigger-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: trigger.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: job-trigger-service
            port:
              number: 80