apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-sidecar
  labels:
    app: myapp
    component: sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      component: sidecar
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: myapp
        component: sidecar
    spec:
      containers:
        - name: logshipper
          image: alpine:latest
          command: ['sh', '-c', 'tail -F /opt/logs.txt']
          volumeMounts:
            - name: data
              mountPath: /opt
      volumes:
        - name: data
          emptyDir: {}