apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: allow-all-egress
spec:
  hosts:
  - "*.amazonaws.com"
  - "*.s3.amazonaws.com"
  - "es.amazonaws.com"
  - "*.googleapis.com"
  - "*.gcr.io"
  - "*.docker.io"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL