# app-test/templates/merge-values-hook.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: merge-values-hook
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: merge-values
        image: alpine/helm:latest
        command: ["sh", "-c"]
        args:
          - |
            helm template app ./app -f values.yaml -f values-dev.yaml > merged-values.yaml
            cat merged-values.yaml
      restartPolicy: Never