apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-with-permissions
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
  volumeMode: Filesystem
  mountOptions:
    - uid=1000
    - gid=2000
    - mode=0770