apiVersion: v1
kind: Service
metadata:
  name: router-service
  labels:
    app: router
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8180
  selector:
    app: router