apiVersion: v1
kind: Service
metadata:
  name: streaming-service-a-tcp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
  - name: streaming
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: streaming-service-a