apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: example
spec:
  containers:
  - name: main-container
    image: nginx
    ports:
    - containerPort: 80
  - name: readiness-manager
    image: busybox
    command: ["sh", "-c"]
    args:
    - |
      # Initial readiness check
      while ! curl -s http://localhost/healthz > /dev/null; do
        sleep 5
      done
      # After initial success, always return ready
      while true; do
        sleep 3600
      done
    readinessProbe:
      exec:
        command: ["sh", "-c", "test -f /tmp/ready || exit 1"]
      initialDelaySeconds: 0
      periodSeconds: 5