apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: your-image:tag
        ports:
        - containerPort: 8080
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - >
              curl --silent --fail --max-time 5 http://localhost:8080/v1/health |
              grep -q '\"status\":\"healthy\"' || exit 1
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 36