apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-deleter-binding
subjects:
- kind: User
  name: <IAM_ROLE_ARN>  # Replace with the ARN of the IAM role attached to the EC2 instance
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-deleter
  apiGroup: rbac.authorization.k8s.io