apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
spec:
  serviceName: ollama
  replicas: 2
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: your-custom-ollama-image:latest
        env:
        - name: MODELS
          value: "llama3.2,llama2"
        ports:
        - containerPort: 11434
        volumeMounts:
        - name: ollama-data
          mountPath: /root/.ollama
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  # Wait for ollama to be ready
                  for i in $(seq 1 30); do
                    if /usr/local/bin/ollama serve --version >/dev/null 2>&1; then
                      break
                    fi
                    sleep 1
                  done
                  # Pull models
                  for model in ${MODELS//,/ }; do
                    /usr/local/bin/ollama pull "$model"
                  done
  volumeClaimTemplates:
  - metadata:
      name: ollama-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi