apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: "mycoolbusinesspod"
              scrape_interval: 5s
              metrics_path: '/actuator/prometheus'
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names: ["default"]  # Replace with your namespace
                  selectors:
                    - role: pod
                      label: "app=mycoolbusinesspod"  # Match your pod's label
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_ip]
                  target_label: __address__
                  replacement: "$1:8080"  # Replace with your pod's port
                - source_labels: [__meta_kubernetes_pod_name]
                  target_label: pod

    processors:
      batch:

    exporters:
      prometheus:
        endpoint: "localhost:8889"

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [prometheus]