apiVersion: v1
kind: ConfigMap
metadata:
  name: adapter-config
  namespace: monitoring
data:
  config.yaml: |
    rules:
    - seriesQuery: 'http_server_requests_seconds_count{namespace!="",service!="",uri="/"}'
      resources:
        overrides:
          namespace: {resource: "namespace"}
          service: {resource: "service"}
      name:
        matches: "http_server_requests_seconds_count"
        as: "http_server_requests_seconds_count"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>,uri!~"/actuator/.*"}[15m])) by (<<.GroupBy>>)'