apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17.4
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: qr-auth-secret
                key: DB_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: qr-auth-secret
                key: DB_USER
          - name: POSTGRES_DB
            value: qr_auth
        command:
          - bash
          - -c
          - |
            set -e
            if [ -z "$(psql -U $(POSTGRES_USER) -l | grep $(POSTGRES_DB))" ]; then
              createdb -U $(POSTGRES_USER) $(POSTGRES_DB)
            fi
            exec docker-entrypoint.sh postgres
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi