apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dir1-write-rolebinding
subjects:
- kind: Group
  name: group1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: dir1-write-role
  apiGroup: rbac.authorization.k8s.io