apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tool-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "off"
spec:
  ingressClassName: nginx
  rules:
  - host: app.example.com
    http:
      paths:
      - path: /tool
        pathType: Prefix
        backend:
          service:
            name: tool-service
            port:
              number: 80