apiVersion: v1
kind: Pod
metadata:
  name: python-memory-aware
spec:
  containers:
  - name: python-app
    image: python:3.10
    resources:
      limits:
        memory: "500Mi"
    command: ["python", "-c"]
    args:
    - |
      import psutil
      import tracemalloc

      # Start memory tracking
      tracemalloc.start()

      def check_memory():
          current = tracemalloc.get_traced_memory()[0] / 1024 / 1024
          limit = 450  # Stay below 450MB to avoid OOM
          if current > limit:
              raise MemoryError(f"Memory usage {current:.2f}MB exceeds limit {limit}MB")

      try:
          # Your memory-intensive code
          data = bytearray(100 * 1024 * 1024)  # 100MB
          check_memory()
          print("Memory usage OK")
      except MemoryError as e:
          print(f"Memory error: {e}")