apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legacy-service-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-retry-middleware@kubernetescrd
spec:
  rules:
    - host: legacy.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: legacy-service
                port:
                  number: 80