apiVersion: v1
kind: Pod
metadata:
  name: database-migrations-debug
  labels:
    app: myapp
    service: myapp-database-migrations
spec:
  shareProcessNamespace: true
  restartPolicy: Never
  containers:
    - name: migrations
      image: registry.example.com/myapp:977b44c9
      imagePullPolicy: Always
      command:
        - bash
        - -c
        - |
          set -e -e
          echo "running database migrations..."
          do-migration-stuff-here
          echo "migrations finished at $(date)"
      volumeMounts:
        - mountPath: /home/example/myapp/app/config/conf.yml
          name: myapp-config-volume
          subPath: conf.yml
        - mountPath: /home/example/myapp/.env
          name: myapp-config-volume
          subPath: .env
    - name: debugger
      image: ubuntu:22.04
      command:
        - bash
        - -c
        - |
          # Debug container: keep shell open
          while true; do sleep 3600; done
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /home/example/myapp/app/config/conf.yml
          name: myapp-config-volume
          subPath: conf.yml
        - mountPath: /home/example/myapp/.env
          name: myapp-config-volume
          subPath: .env
  volumes:
    - name: myapp-config-volume
      configMap:
        name: myapp
  imagePullSecrets:
    - name: k8s-pull-project