apiVersion: v1
kind: Pod
metadata:
  name: rails-nginx-shared-assets
  labels:
    app: rails-nginx
spec:
  restartPolicy: Always

  volumes:
  - name: shared-assets
    emptyDir: {}

  containers:
  - name: rails-app
    image: your-registry/your-rails-image:latest
    # This container copies prebuilt assets from the image into the shared volume
    command: ["/bin/sh"]
    args:
      - -c
      - >
        cp -r /app/your-app-name/public/* /shared-assets/ &&
        # start your real rails command here, for example:
        bundle exec puma -C config/puma.rb
    volumeMounts:
    - name: shared-assets
      mountPath: /shared-assets
    # other env, ports, etc. for the Rails app
    env:
    - name: RAILS_ENV
      value: "production"

  - name: nginx
    image: nginx:stable
    volumeMounts:
    - name: shared-assets
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - name: http
      containerPort: 80
    # you can also mount an nginx.conf via ConfigMap if needed