apiVersion: v1
kind: Service
metadata:
  name: app-api-redis-svc
  labels:
    app: app-api-redis
    tier: celery_broker
spec:
  # ClusterIP is the default; this keeps Redis internal-only
  type: ClusterIP
  selector:
    app: app-api-redis
    tier: celery_broker
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379