apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpg-app-ingress
  namespace: default
  annotations:
    # Use the nginx ingress controller
    kubernetes.io/ingress.class: "nginx"
    # No rewrite-target: we want the backend to see /something unchanged
spec:
  ingressClassName: nginx
  rules:
  - host: example.com
    http:
      paths:
      - path: /something
        pathType: Prefix
        backend:
          service:
            name: example-com
            port:
              number: 80