apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
  namespace: default
  labels:
    app: mongodb
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017        # Cluster-internal port
      targetPort: 27017  # MongoDB container port
      nodePort: 32017    # External port on each node (must be in 30000-32767)
      protocol: TCP