apiVersion: v1
kind: Config
clusters:
  - name: dev-cluster
    cluster:
      server: https://10.11.12.14:8888
      # In production, also specify certificate-authority or certificate-authority-data
      # certificate-authority-data: BASE64_CA_CERT_HERE
contexts:
  - name: kubernetes-admin-dev@dev-cluster
    context:
      cluster: dev-cluster
      user: kubernetes-admin-dev
current-context: kubernetes-admin-dev@dev-cluster
users:
  - name: kubernetes-admin-dev
    user:
      client-certificate-data: aabbcc
      client-key-data: aabbcc