apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  gcePersistentDisk:
    pdName: gce-nfs-disk
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain