apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app: ingress-nginx-controller
  externalIPs:
    - 203.0.113.2
    - 203.0.113.3
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30100
    - name: https
      port: 443
      targetPort: https
      nodePort: 30101