apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - api-sand.fake.com
  rules:
    - host: api-sand.fake.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-sand
                port:
                  number: 80