apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 4800Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-1234567890abcdef0
    volumeAttributes:
      dnsname: fs-1234567890abcdef0.fsx.us-east-1.amazonaws.com
      mountname: abcdef01