apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: test.kubetest.lff.bybn.de
      http:
        paths:
          - path: /abc
            pathType: Prefix
            backend:
              service:
                name: app-service
                port:
                  number: 80