apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: microservice
  namespace: default
  labels:
    app.kubernetes.io/name: microservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # Target average CPU utilization (as a percentage of requested CPU)
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          # Target average memory utilization (as a percentage of requested memory)
          averageUtilization: 75