apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: i-storage-ca-issuer-prod
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: my_email_here
    privateKeySecretRef:
      name: i-storage-ca-issuer-prod
    solvers:
      - http01:
          ingress:
            class: gce-internal