apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: my-apps
  name: my-apps-qbrjf
  namespace: test-systems
spec:
  host: www.test.gov.tw
  port:
    targetPort: http
  to:
    kind: Service
    name: my-apps
    weight: 100
  wildcardPolicy: None