apiVersion: apps/v1
kind: Deployment
metadata:
  name: vod-deployment
  labels:
    app: vod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vod
  template:
    metadata:
      labels:
        app: vod
    spec:
      initContainers:
      - name: chown-volumes
        image: busybox:latest  # Use a lightweight image for chown operation
        command: ["sh", "-c", "chown -R 1000:1000 /opt/tools/aptm /aptm"]
        volumeMounts:
        - name: aptm-data
          mountPath: /opt/tools/aptm
        - name: aptm-data-glowroot
          mountPath: /aptm
        securityContext:
          runAsUser: 0  # Run as root to perform chown
          runAsGroup: 0
          runAsNonRoot: false
          readOnlyRootFilesystem: true
      - name: glowroot-jar-init-container
        image: example-registry/example-aptm-image:latest  # Rendered from {{ .Values.images.repository }}/{{ .Values.config.aptm.image }}
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        imagePullPolicy: Always  # Rendered from {{ .Values.images.pullPolicy }}
        command: ["cp", "/opt/tools/aptm/glowroot.jar", "/aptm"]
        volumeMounts:
        - name: aptm-data-glowroot
          mountPath: /aptm
      containers:
      - name: vod-container  # Rendered from {{ template "name" . }}
        image: example-registry/com.gtt.ecomp.vod.dev/vod:latest  # Rendered from {{ .Values.images.repository }}/com.gtt.ecomp.vod.dev/vod:{{ .Values.images.vodTag }}
        imagePullPolicy: Always  # Rendered from {{ .Values.images.pullPolicy }}
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        command:
        - sh
        - -c
        - |
          echo "Copying aptm JAR."
          cp /usr/local/tomcat/webapps/vod/WEB-INF/lib/hram-agent-0.13.jar /opt/tools/aptm;
          bash /mounted-config/start_tomcat.sh;
        args:
        - "30000"
        volumeMounts:
        - name: aptm-data
          mountPath: /opt/tools/aptm
        - name: aptm-data-glowroot
          mountPath: /aptm
        # Assuming other mounts like /mounted-config are defined elsewhere
      volumes:
      - name: aptm-data
        emptyDir: {}
      - name: aptm-data-glowroot
        emptyDir: {}
      # Assuming other volumes are defined elsewhere