apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-gateway
  namespace: default
spec:
  selector:
    app: spring-cloud-gateway
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer  # Or ClusterIP/Ingress as needed