apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-database-config: "database/config"
        vault.hashicorp.com/secret-volume-path: "/app/conf"
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{ with secret "database/config" -}}
          {
            "username": "{{ .Data.username }}",
            "password": "{{ .Data.password }}"
          }
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: app
        image: your-app-image:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: vault-secrets
          mountPath: /app/conf
          readOnly: true
      volumes:
      - name: vault-secrets
        emptyDir: {}