apiVersion: v1
kind: Pod
metadata:
  name: blue-pod-cka
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: blue-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: blue-volume
      persistentVolumeClaim:
        claimName: blue-pvc-cka
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
  # Added tolerations for production readiness if scheduling on control-plane nodes
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  # Added security context for production readiness
  securityContext:
    runAsNonRoot: true
    runAsUser: 101  # nginx user ID