apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/component: Ingress
  name: amq-artemis
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hidden
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    cert-manager.io/cluster-issuer: hidden
    cert-manager.io/duration: 2160h
    cert-manager.io/renew-before: 720h
    nginx.ingress.kubernetes.io/keepalive_timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-body-size: "250m"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4 256k"
    nginx.ingress.kubernetes.io/proxy-buffering: 'on'
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "amq-artemis"
    nginx.ingress.kubernetes.io/session-cookie-samesite: "Lax"
    nginx.ingress.kubernetes.io/session-cookie-secure: "true"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    nginx.ingress.kubernetes.io/app-root: /console/artemis
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://hidden"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_busy_buffers_size   256k;
      client_body_buffer_size   10m;
      send_timeout              300;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hidden
      secretName: artemis-fqdn-cert
  rules:
    - host: hidden
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: amq-artemis
              port:
                number: 8161
        - path: /jolokia
          pathType: Prefix
          backend:
            service:
              name: amq-artemis
              port:
                number: 8161
        - path: /hawtio
          pathType: Prefix
          backend:
            service:
              name: amq-artemis
              port:
                number: 8161
        - path: /console
          pathType: Prefix
          backend:
            service:
              name: amq-artemis
              port:
                number: 8161