apiVersion: v1
kind: Service
metadata:
  name: micro-app-service
  namespace: default
spec:
  selector:
    app: micro-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP