apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless  # Renamed for consistency with StatefulSet
  namespace: default
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181