apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-config-full-dns
  namespace: default  # Adjust to match your Spring Boot app's namespace if different
data:
  application.yml: |
    spring:
      application:
        version: 1.0.0
        name: scpi-invest-plus-partner
      kafka:
        bootstrap-servers: kafka-0.kafka-headless.default.svc.cluster.local:9092,kafka-1.kafka-headless.default.svc.cluster.local:9092,kafka-2.kafka-headless.default.svc.cluster.local:9092  # Added full DNS qualification for headless service in default namespace
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        consumer:
          group-id: scpi-partner-group
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          properties:
            spring.json.trusted.packages: "*"