apiVersion: v1
kind: Service
metadata:
  name: telemetry-asterix-adapter-svc
  namespace: utm
spec:
  type: LoadBalancer
  selector:
    app: telemetry-asterix-adapter
  ports:
  - name: udp-1025
    protocol: UDP
    port: 1025
    targetPort: 6000
  loadBalancerSourceRanges:
  - 71.###.###.###/32
  - 71.###.###.###/32
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  allocateLoadBalancerNodePorts: true