apiVersion: v1
kind: Pod
metadata:
  name: my-test-pod
  namespace: default
  labels:
    app: my-app
spec:
  restartPolicy: Never
  containers:
  - name: my-container
    image: nginx:latest  # Replace with your actual image
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 101  # Example for nginx
      capabilities:
        drop:
        - ALL
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
  dnsPolicy: ClusterFirst
  restartPolicy: Never