apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: overlay
resources:
- deployment.yaml  # Your base Deployment file with $(SVC_NAME) placeholders
configMapGenerator:
- name: svc-config
  literals:
  - name=svc1
vars:
- name: SVC_NAME
  objref:
    kind: ConfigMap
    name: svc-config
    apiVersion: v1
  fieldref:
    fieldpath: data.name