apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  {{- include "commonMeta" . | nindent 2 }}
data:
  config.play.ts: |
    const config = {
      "PORT": {{ .Values.app.play.PORT }},
      "PLAY_EXPIRES_IN_MS": {{ .Values.app.play.PLAY_EXPIRES_IN_MS }},
      "API_URL": "{{ .Values.app.play.API_URL }}",
    };
    export default config;