apiVersion: v1
kind: Deployment
metadata:
  name: aspnet-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet-app
  template:
    metadata:
      labels:
        app: aspnet-app
    spec:
      containers:
      - name: aspnet-app
        image: your-aspnet-app:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "https://+:443;http://+:80"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "/root/.aspnet/https/aspnetapp.pfx"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: aspnet-cert-password
              key: password
        volumeMounts:
        - name: user-secrets
          mountPath: /root/.microsoft/usersecrets
          readOnly: true
        - name: aspnet-https
          mountPath: /root/.aspnet/https
          readOnly: true
      volumes:
      - name: user-secrets
        hostPath:
          path: /run/desktop/mnt/host/c/Users/YOUR_USERNAME/AppData/Roaming/Microsoft/UserSecrets
          type: Directory
      - name: aspnet-https
        hostPath:
          path: /run/desktop/mnt/host/c/Users/YOUR_USERNAME/AppData/Roaming/ASP.NET/Https
          type: Directory