apiVersion: v1
kind: Pod
metadata:
  name: app-with-extended-intervals
  labels:
    app: myapp
spec:
  containers:
  - name: app
    image: myapp:latest
    ports:
    - containerPort: 8080
    startupProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 0
      periodSeconds: 3
      timeoutSeconds: 2
      successThreshold: 1
      failureThreshold: 60  # 3 minutes max startup
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 0
      periodSeconds: 600  # Check every 10 minutes
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 1