apiVersion: v1
kind: Pod
metadata:
  name: my-test-app-pod-2
  namespace: default
  labels:
    app: my-test-app
spec:
  restartPolicy: Never
  containers:
  - name: app-container
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"