apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: common-base
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: svc1
        labels:
          app: svc1